insert into categories(id, name) values(1, 'Доход');
insert into categories(id, name) values(2, 'Продукты');
insert into categories(id, name) values(3, 'Одежда');
insert into categories(id, name) values(4, 'Обувь');
insert into categories(id, name) values(5, 'Мебель');
insert into categories(id, name) values(6, 'Сантехника');
insert into categories(id, name) values(7, 'Развлечения');
insert into categories(id, name) values(8, 'Отдых');
insert into categories(id, name) values(9, 'Операции с платежными картами');
insert into categories(id, name) values(10, 'Операции с валютой');
insert into categories(id, name) values(11, 'Коммунальные услуги');
insert into categories(id, name) values(12, 'Недвижимость');
insert into categories(id, name) values(13, 'Расход');
insert into categories(id, name) values(14, 'Техника');
insert into categories(id, name) values(15, 'Бытовая химия');
insert into categories(id, name) values(16, 'Лекарства');
insert into categories(id, name) values(17, 'Табачные изделия');
insert into categories(id, name) values(18, 'Алкоголь');
insert into categories(id, name) values(19, 'Товары для кухни');
insert into categories(id, name) values(20, 'Мобильная связь');
insert into categories(id, name) values(21, 'Интернет');
insert into categories(id, name) values(22, 'Косметика');
insert into categories(id, name) values(23, 'Автомобиль');
insert into categories(id, name) values(24, 'Транспорт');
insert into categories(id, name) values(25, 'Товары для животных');
insert into categories(id, name) values(26, 'Средства личной гигиены');
insert into categories(id, name) values(27, 'Бижутерия');
insert into categories(id, name) values(28, 'Товары для детей');
insert into categories(id, name) values(29, 'Инструменты');
insert into categories(id, name) values(30, 'Галантерея');
insert into categories(id, name) values(31, 'Услуги');
insert into categories(id, name) values(32, 'Канцелярские товары');
insert into categories(id, name) values(33, 'Собака');
insert into categories(id, name) values(34, 'Командировка');
insert into categories(id, name) values(35, 'Радиодетали');
